### ISSUE TITLE
README.md linking for dev use instructions fail

### ISSUE THREAD

**Issue by benvand** [alphagov/digitalmarketplace-frameworks#412]
As far as I can make out this package shouldn't have a `node_modules` directory because it has no `node.js` dependencies.
https://github.com/alphagov/digitalmarketplace-frameworks/blame/master/README.md#L134

Therefore this won't work:
```
A local checkout of the frameworks repo can be shared with locally-running services (i.e. frontend applications)
as follows:

- from this repo, run `node_modules/bower/bin/bower link`
- from each app, run `node_modules/bower/bin/bower link digitalmarketplace-frameworks`
```

I've worked around this by installing bower globally and linking this package globally like so:
```
- from anywhere, run `sudo npm install -g bower`
- from this repo, run `bower link`
- from each app, run `bower link digitalmarketplace-frameworks` or `node_modules/bower/bin/bower link digitalmarketplace-frameworks`
```

I'm not much of an `npm` / `bower` guy so I'll need some input as to whether or not this has any caveats @galund

**Comment by TheDoubleK** [comment]
Weird - I'm sure people have had the bower link stuff up and running in the past.

**Comment by galund** [comment]
This is clearly my fault, I think I probably copy-pasted my new instructions from another repo (the instructions about this were missing from all of them).

You can certainly install bower globally, or alternatively use any of the bowers that you've installed elsewhere (if you give a full path). Feel free to update the readme, it'd be nice if it made sense. 

Otherwise, assign me this issue, and I might get around to it sometime :)

**Comment by TheDoubleK** [comment]
I reckon it'd be nice to avoid recommending global bower.

**Comment by benvand** [comment]
Maybe a  makefile command or something.
`make bower_link <my_local_frameworks>`

To be run from each of the frontends.

**Comment by galund** [comment]
If `make` is to run bower, it still has to be able to find it somewhere :/

**Comment by galund** [comment]
Oh, no I understood what you mean now. Yep.

**Comment by carolinegreen** [comment]
I don't like installing things globally either but Bower is generally designed to be installed globally as it's a node command line tool.

https://docs.npmjs.com/getting-started/installing-npm-packages-globally

**Comment by galund** [comment]
Saw this ticket and felt ashamed... I've updated the readme, I didn't include the `sudo` because it wasn't necessary for me, and hopefully wouldn't be for anyone else as long as npm is set up right.

https://github.com/alphagov/digitalmarketplace-frameworks/pull/485

**Comment by galund** [comment]
Readme fixed up, merged.
