### ISSUE TITLE
Apply number formatting for prices

### ISSUE THREAD

**Issue by mvl22** [alphagov/digitalmarketplace-frameworks#626]
In the pricing section for GCloud 12 (and presumably other frameworks), the prices are not formatted with commas.

Adding such formatting would make them easier to parse visually, and avoid misreadings.

E.g. £30,000 is shown currently as £30000.

![Screen Shot 2020-07-20 at 01 02 20](https://user-images.githubusercontent.com/361423/87888439-d33f5d00-ca24-11ea-8cb7-d968fef068ba.png)

**Comment by katstevens** [comment]
Thanks for raising this @mvl22, we'll add it to our backlog.

**Comment by alex9smith** [comment]
A fix for this has now been deployed, thanks for bringing it to our attention.
